// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package observe

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ObserveClient is the client API for Observe service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ObserveClient interface {
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type observeClient struct {
	cc grpc.ClientConnInterface
}

func NewObserveClient(cc grpc.ClientConnInterface) ObserveClient {
	return &observeClient{cc}
}

func (c *observeClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/observe.Observe/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObserveServer is the server API for Observe service.
// All implementations must embed UnimplementedObserveServer
// for forward compatibility
type ObserveServer interface {
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedObserveServer()
}

// UnimplementedObserveServer must be embedded to have forward compatible implementations.
type UnimplementedObserveServer struct {
}

func (UnimplementedObserveServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedObserveServer) mustEmbedUnimplementedObserveServer() {}

// UnsafeObserveServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ObserveServer will
// result in compilation errors.
type UnsafeObserveServer interface {
	mustEmbedUnimplementedObserveServer()
}

func RegisterObserveServer(s grpc.ServiceRegistrar, srv ObserveServer) {
	s.RegisterService(&Observe_ServiceDesc, srv)
}

func _Observe_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObserveServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/observe.Observe/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObserveServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Observe_ServiceDesc is the grpc.ServiceDesc for Observe service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Observe_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "observe.Observe",
	HandlerType: (*ObserveServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _Observe_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "observe.proto",
}
