name: ci
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout scm
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - name: Install protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'
      - name: Install protoc extensions
        run: |
          go get github.com/golang/protobuf/protoc-gen-go
          go get google.golang.org/grpc/cmd/protoc-gen-go-grpc
      - name: Generate proto/gRPC code
        run: make generate
      - name: Build
        run: make build
